### ISSUE TITLE
The next GSoC

### ISSUE THREAD

**Issue by chris001** [OfflineIMAP/imapfw#13]
Hello Nicolas,
I read the sad blog entry about the 2016 GSoC and how Gentoo organization didn't select imapfw because another project was more relevant to the their operating system distro.

I wanted to encourage you to try it again with an OfflineIMAP.org organization (similar to `jisti.org` which is also tiny, and many other small github organizations) and apply for the next GSoC.
https://summerofcode.withgoogle.com/organizations/?sp-page=3

"What are the eligibility requirements for a mentoring organization?

To be eligible to participate as a mentoring organization, you must be a group running an active free/open source software project, e.g. BRL-CAD. **The project does not need to be a legally incorporated entity.** Mentoring organizations must have already produced and released software under an Open Source Initiative approved license and have at least two contributors to serve as organization administrators and/or mentors for the entire program in order to participate in the program."

https://developers.google.com/open-source/gsoc/faq

**Comment by nicolas33** [comment]
Hi Chris,

Yes, I know the rules since I've read all the available documentation last year. Also, I'm still subscribed to the official GSoC mailing list.

I've called for volunteers at the offlineimap mailing list in January to participate to GSoC 2017 but nobody replied. 

```
Hey,

GSoC 2017 has officially begun. Organizations application is open
through Februrary 9th.

I'm calling for mentors to support either imapfw or offlineimap.

Learn more about GSoC at

  https://developers.google.com/open-source/gsoc/

We applied in 2016. The GSoC page of 2016 is

  http://www.offlineimap.org/gsoc/

We had good proposals from students.

This year, we would apply as the OfflineIMAP org or with the Python org.

Let me know if you'd like to mentor students this summer. I'd like to
hear from you for comments and new project ideas.

Regards,
```

Now it's too late. Google doesn't accept orgs anymore.

If I have time enough to be involved myself or if there are volunteers to participate, we might like to try next year.

As said in the mail, this could be done directly or within another umbrella org like [Python](http://python-gsoc.org/), I don't know. I think this is best decided with the project mentors when the time comes. ,-)

**Comment by chris001** [comment]
I think it would be best done directly as its own org, because any umbrella org has its own agenda which probably does not coincide with OfflineIMAP org's agenda.  As happened with Gentoo. :(
