### ISSUE TITLE
UID Move/UID Copy

### ISSUE THREAD

**Issue by cmcaine** [OfflineIMAP/imapfw#2]
Hi,

The readme suggests that imapfw will use UIDPLUS and/or UID MOVE capabilities. Is this so? When do you think these capabilities might be implemented.

I believe that offlineimap does not use these capabilities when moving mail between folders. Is that correct? If so, do you think it might be an easy fix?

Thanks,
Colin

**Comment by nicolas33** [comment]
Hi Colin,

Yes, I intend to implement UID MOVE and UIDPLUS while they are not in the primary list. I don't expect imapfw to become production ready soon. It might be ready in a year or so. First stable releases could be without those features.

However, due to the controller design, implementing such feature should be made easier than in OfflineIMAP.

OfflineIMAP does not support UIDPLUS and UID MOVE. Implementing such feature in OfflineIMAP is hard.

**Comment by cmcaine** [comment]
Hi Nicolas,

Thanks for your response and best of luck with imapfw :)
